### ISSUE TITLE
Add benchmarks for batch write?

### ISSUE THREAD

**Issue by jarifibrahim** [smallnest/kvbench#8]
Hi, Thank you for creating these benchmarks. They are very helpful. 
I work on badger and I realized your benchmark code uses `transaction.Set` with **single entries** in the `testSet`. Do you think it would be useful to compare the batch writer as well? Badger has a batch writer which is much faster than single entry writes.

Single entry writes are the slowest way of writing data to badger. I can help with writing the benchmark for write batch. 

Thank you once again for the benchmarks :)

**Comment by smallnest** [comment]
You are welcome to add more cases.thanks
